# Generated by Django 3.2.12 on 2022-04-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_user',
            name='username',
            field=models.CharField(max_length=24, unique=True, verbose_name='Юзернейм'),
        ),
    ]
