# Generated by Django 3.2.12 on 2022-04-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_todouser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TODO_User',
        ),
    ]
